name: Code verification

on:
    push:
        branches:
            - master
    pull_request:
jobs:
    code-verification:
        name: Code Check
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Cache maven dependences
                uses: actions/cache@v2
                env:
                    maven-cache-key: maven-cache
                    maven-path: ~/.m2
                with:
                    path: ${{ env.maven-path }}
                    key: ${{ runner.os }}-build-${{ env.maven-cache-key }}-${{ hashFiles('pom.xml') }}
            -   name: Run tests check
                run: mvn clean verify

            -   name: SonarCloud Scan
                uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
